# Generated by Django 3.1.4 on 2020-12-20 17:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route_optimization', '0001_super_user_pgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('phone', models.CharField(max_length=20)),
                ('driver', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transportable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
            ],
        ),
    ]
